// The NOTICE file: every third-party package compiled into main.js, with the licence it carries,
// verbatim. This plugin is Apache-2.0 and is distributed as one bundled file, and the licences of
// what it bundles — MIT for all but its own meta-model — ask that their notice travel with any
// substantial portion of the code. A bundle is the whole of it, so the notice travels here.
//
// Generated rather than written: a dependency added or moved changes what must be listed, and a
// list kept by hand is one that silently stops being true. `npm run notices` writes the file and
// test/notices.test.ts fails when what is written no longer matches the tree.
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

// The packages that end up in the bundle: the production tree, which is what esbuild follows.
// devDependencies build it and are not in it, and what `external` leaves out — Obsidian's own API
// and CodeMirror — is supplied by the application and is not ours to license.
export function bundled(root = ".") {
  const out = execFileSync("npm", ["ls", "--prod", "--all", "--parseable"], { cwd: root, encoding: "utf8" });
  const names = out
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.includes("/node_modules/"))
    .map((line) => line.slice(line.lastIndexOf("/node_modules/") + "/node_modules/".length));
  return [...new Set(names)].sort();
}

// A package's own licence file, whatever it is called, and the identifier it declares.
function licenceOf(root, name) {
  const dir = join(root, "node_modules", name);
  const meta = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  const file = readdirSync(dir).find((entry) => /^licen[cs]e/i.test(entry));
  return {
    version: meta.version ?? "",
    // A package with no `license` field says so rather than being quietly left out.
    id: typeof meta.license === "string" ? meta.license : "declared in its licence file",
    text: file ? readFileSync(join(dir, file), "utf8").trimEnd() : "",
  };
}

const RULE = "-".repeat(78);

export function noticeOf(root = ".") {
  const self = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
  const packages = bundled(root);
  const head = [
    `${self.name}`,
    `Copyright the CompanyGraph authors`,
    "",
    "This product is licensed under the Apache License, Version 2.0; see LICENSE.",
    "",
    "It is distributed as one bundled file, main.js, which compiles in the packages",
    `listed below — ${packages.length} of them. Each is reproduced here with the licence it`,
    "carries, because a bundle is a substantial portion of each and their licences ask",
    "that this notice travel with it.",
    "",
    "This file is generated by scripts/notices.mjs from the installed production tree.",
    "Run `npm run notices` after changing a dependency; a test fails when it is stale.",
    "",
  ];
  const body = packages.flatMap((name) => {
    const { version, id, text } = licenceOf(root, name);
    return [RULE, `${name}@${version} — ${id}`, RULE, "", text, ""];
  });
  return [...head, ...body].join("\n").trimEnd() + "\n";
}

if (process.argv[1] && process.argv[1].endsWith("notices.mjs")) {
  const { writeFileSync } = await import("node:fs");
  const text = noticeOf(".");
  writeFileSync("NOTICE", text);
  console.log(`NOTICE written: ${bundled(".").length} packages, ${text.length} bytes`);
}
